const SHOP_DATA_PRODUCTS = [
  {
    id: 1,
    name: 'Brown Brim',
    imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
    category : "hats",
    price: 25,
  },
  {
    id: 2,
    name: 'Blue Beanie',
    imageUrl: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
    category : "hats",
    price: 18,
  },
  {
    id: 3,
    name: 'Brown Cowboy',
    imageUrl: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png',
    category : "hats",
    price: 35,
  },
  {
    id: 4,
    name: 'Grey Brim',
    imageUrl: 'https://i.ibb.co/RjBLWxB/grey-brim.png',
    category : "hats",
    price: 25,
  },
  {
    id: 5,
    name: 'Green Beanie',
    imageUrl: 'https://i.ibb.co/YTjW3vF/green-beanie.png',
    category : "hats",
    price: 18,
  },
  {
    id: 6,
    name: 'Palm Tree Cap',
    imageUrl: 'https://i.ibb.co/rKBDvJX/palm-tree-cap.png',
    category : "hats",
    price: 14,
  },
  {
    id: 7,
    name: 'Red Beanie',
    imageUrl: 'https://i.ibb.co/bLB646Z/red-beanie.png',
    category : "hats",
    price: 18,
  },
  {
    id: 8,
    name: 'Wolf Cap',
    imageUrl: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
    category : "hats",
    price: 14,
  },
  {
    id: 9,
    name: 'Blue Snapback',
    imageUrl: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
    category : "hats",
    price: 16,
  },
  {
    id: 10,
    name: 'Adidas NMD',
    imageUrl: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
    category : "sneakers",
    price: 220,
  },
  {
    id: 11,
    name: 'Adidas Yeezy',
    imageUrl: 'https://i.ibb.co/dJbG1cT/yeezy.png',
    category : "sneakers",
    price: 280,
  },
  {
    id: 12,
    name: 'Black Converse',
    imageUrl: 'https://i.ibb.co/bPmVXyP/black-converse.png',
    category : "sneakers",
    price: 110,
  },
  {
    id: 13,
    name: 'Nike White AirForce',
    imageUrl: 'https://i.ibb.co/1RcFPk0/white-nike-high-tops.png',
    category : "sneakers",
    price: 160,
  },
  {
    id: 14,
    name: 'Nike Red High Tops',
    imageUrl: 'https://i.ibb.co/QcvzydB/nikes-red.png',
    category : "sneakers",
    price: 160,
  },
  {
    id: 15,
    name: 'Nike Brown High Tops',
    imageUrl: 'https://i.ibb.co/fMTV342/nike-brown.png',
    category : "sneakers",
    price: 160,
  },
  {
    id: 16,
    name: 'Air Jordan Limited',
    imageUrl: 'https://i.ibb.co/w4k6Ws9/nike-funky.png',
    category : "sneakers",
    price: 190,
  },
  {
    id: 17,
    name: 'Timberlands',
    imageUrl: 'https://i.ibb.co/Mhh6wBg/timberlands.png',
    category : "sneakers",
    price: 200,
  },
  {
    id: 18,
    name: 'Black Jean Shearling',
    imageUrl: 'https://i.ibb.co/XzcwL5s/black-shearling.png',
    category:"jackets",
    price: 125,
  },
  {
    id: 19,
    name: 'Blue Jean Jacket',
    imageUrl: 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png',
    category:"jackets",
    price: 90,
  },
  {
    id: 20,
    name: 'Grey Jean Jacket',
    imageUrl: 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png',
    category:"jackets",
    price: 90,
  },
  {
    id: 21,
    name: 'Brown Shearling',
    imageUrl: 'https://i.ibb.co/s96FpdP/brown-shearling.png',
    category:"jackets",
    price: 165,
  },
  {
    id: 22,
    name: 'Tan Trench',
    imageUrl: 'https://i.ibb.co/M6hHc3F/brown-trench.png',
    category:"jackets",
    price: 185,
  },
  {
    id: 23,
    name: 'Camo Down Vest',
    imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
    category:"mens",
    price: 325,
  },
  {
    id: 24,
    name: 'Floral T-shirt',
    imageUrl: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
    category:"mens",
    price: 20,
  },
  {
    id: 25,
    name: 'Black & White Longsleeve',
    imageUrl: 'https://i.ibb.co/55z32tw/long-sleeve.png',
    category:"mens",
    price: 25,
  },
  {
    id: 26,
    name: 'Pink T-shirt',
    imageUrl: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
    category:"mens",
    price: 25,
  },
  {
    id: 27,
    name: 'Jean Long Sleeve',
    imageUrl: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
    category:"mens",
    price: 40,
  },
  {
    id: 28,
    name: 'Burgundy T-shirt',
    imageUrl: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
    category:"mens",
    price: 25,
  }
]
export default SHOP_DATA_PRODUCTS;